# Makefile for Sd/Sdtty for Solaris

# This gives the compiler name and any switches that it needs to make
# it operate the way we want (ANSI language, standards conformance,
# target hardware, etc.)
CC = gcc

# This gives any "-D" switches that we always need to send to the compiler.
DEFS = -Wall -Wno-switch -Wno-uninitialized -Wno-char-subscripts

# This gives the optimization and/or debug info.  These flags presumably
# don't affect the semantics of the language and run-time environment, so you
# might reasonably want to change them to suit your taste.
# The options shown here have been chosen to optimize the program for
# production use.  Depending on your operating system, compiler, and debugger,
# this may compromise the ability to debug the program.  In this case, you may
# need to choose different options, typically "-g", for debugging.
# Consult your system, compiler, and debugger vendor for further information.
CDEBUGFLAGS = -O2

CFLAGS =$(CDEBUGFLAGS) $(DEFS)

# These are the "-I"  and "-D" flags that we must use for the compilation
# of the X11 user interface (sdui-x11.c).
X11_FLAGS =

# These are the "-I"  and "-D" flags that we must use for the compilation
# of the system-dependent part of the TTY user interface (sdui-ttu.cpp).
# "-DNO_CURSES"	- disable compilation with curses.
#
TTY_FLAGS =

# These are the library flags that we must use for the final bind of
# the X11 version of "sd".
X11_LIBS =

# These are the library flags that we must use for the final bind of
# "sdtty".
#
# Static curses libraries are used in the Solaris build to avoid
#	portability issues.
TTY_LIBS = /usr/lib/libcurses.a

SD_SRCS = sdmain.cpp sdutil.cpp sdbasic.cpp sdinit.cpp \
          sdtables.cpp sdctable.cpp sdtop.cpp sdconcpt.cpp sdpreds.cpp \
          sdgetout.cpp sdmoves.cpp sdtand.cpp sdconc.cpp sdistort.cpp \
          sdpick.cpp sdsi.cpp

SD_OBJS = sdmain.o sdutil.o sdbasic.o sdinit.o \
          sdtables.o sdctable.o sdtop.o sdconcpt.o sdpreds.o \
          sdgetout.o sdmoves.o sdtand.o sdconc.o sdistort.o \
          sdpick.o sdsi.o

SDX11_SRC = sdui-x11.c
SDX11_OBJ = sdui-x11.o

SDTTY_SRCS = sdui-tty.cpp sdmatch.cpp sdui-ttu.cpp
SDTTY_OBJS = sdui-tty.o sdmatch.o sdui-ttu.o

SDTTY_LINK_OBJS = $(SD_OBJS) $(SDTTY_OBJS)

MKCALLS_SRCS = mkcalls.cpp dbcomp.cpp
MKCALLS_OBJS = mkcalls.o dbcomp.o

SRCS = $(SD_SRCS) $(SDX11_SRC) $(SDTTY_SRCS) $(MKCALLS_SRCS)
OBJS = $(SD_OBJS) $(SDX11_OBJ) $(SDTTY_OBJS) $(MKCALLS_OBJS)

all: alltty
allx11: sd sd_calls.dat
alltty: sdtty sd_calls.dat
everything: allx11 sdtty

LDPRELIBS =
LDPOSTLIBS = lib\crt0.o lib\libc.a

sd: $(SD_OBJS) $(SDX11_OBJ)
	$(CC) $(CFLAGS) -o $@ $(SD_OBJS) $(SDX11_OBJ) $(LDPRELIBS) $(X11_LIBS) $(LDPOSTLIBS)

mkcalls: $(MKCALLS_OBJS)
	$(CC) $(CFLAGS) -o $@ $(MKCALLS_OBJS)

sdtty: $(SD_OBJS) $(SDTTY_OBJS)
	$(CC) $(CFLAGS) -o $@ $(SDTTY_LINK_OBJS) $(TTY_LIBS)

sd_calls.dat: sd_calls.txt mkcalls
	./mkcalls ./sd_calls.txt

.SUFFIXES: .c .cpp

.c.o:
	$(CC) $(CFLAGS) -c $<

.cpp.o:
	$(CC) $(CFLAGS) -c $<

sdui-x11.o: sdui-x11.c
	$(CC) $(CFLAGS) $(X11_FLAGS) -c $<

sdui-ttu.o: sdui-ttu.cpp
	$(CC) $(CFLAGS) $(TTY_FLAGS) -c $<

dbcomp.o sdmain.o sdsi.o sdui-x11.o: paths.h

dbcomp.o: database.h

$(SD_OBJS) $(SDX11_OBJ) $(SDTTY_OBJS): sd.h database.h

clean::
	-$(RM) *.o sd sdtty mkcalls sd_calls.dat tags

TAG_FILES = ${SRCS} *.h

tags: ${TAG_FILES}
	/opt/sfw/bin/ctags ${TAG_FILES}
